$folder="E:\LCC";             # Directory to place the new folders in.

new-item -path $folder\ -Name "AC Collections Series Collected works.md" -ItemType "file"
new-item -path $folder\ -Name "AE Encyclopedias.md" -ItemType "file"
new-item -path $folder\ -Name "AG Dictionaries and other general reference works.md" -ItemType "file"
new-item -path $folder\ -Name "AI Indexes.md" -ItemType "file"
new-item -path $folder\ -Name "AM Museums Collectors and collecting.md" -ItemType "file"
new-item -path $folder\ -Name "AN Newspapers.md" -ItemType "file"
new-item -path $folder\ -Name "AP Periodicals.md" -ItemType "file"
new-item -path $folder\ -Name "AS Academies and learned societies.md" -ItemType "file"
new-item -path $folder\ -Name "AY Yearbooks Almanacs Directories.md" -ItemType "file"
new-item -path $folder\ -Name "AZ History of scholarship and learning The humanities.md" -ItemType "file"
new-item -path $folder\ -Name "B Philosophy General.md" -ItemType "file"
new-item -path $folder\ -Name "BC Logic.md" -ItemType "file"
new-item -path $folder\ -Name "BD Speculative philosophy.md" -ItemType "file"
new-item -path $folder\ -Name "BF Psychology.md" -ItemType "file"
new-item -path $folder\ -Name "BH Aesthetics.md" -ItemType "file"
new-item -path $folder\ -Name "BJ Ethics.md" -ItemType "file"
new-item -path $folder\ -Name "BL Religions Mythology Rationalism.md" -ItemType "file"
new-item -path $folder\ -Name "BM Judaism.md" -ItemType "file"
new-item -path $folder\ -Name "BP Islam Bahaism Theosophy etc.md" -ItemType "file"
new-item -path $folder\ -Name "BQ Buddhism.md" -ItemType "file"
new-item -path $folder\ -Name "BR Christianity.md" -ItemType "file"
new-item -path $folder\ -Name "BS The Bible.md" -ItemType "file"
new-item -path $folder\ -Name "BT Doctrinal theology.md" -ItemType "file"
new-item -path $folder\ -Name "BV Practical Theology.md" -ItemType "file"
new-item -path $folder\ -Name "BX Christian Denominations.md" -ItemType "file"
new-item -path $folder\ -Name "C Auxiliary Sciences of History.md" -ItemType "file"
new-item -path $folder\ -Name "CB History of Civilization.md" -ItemType "file"
new-item -path $folder\ -Name "CC Archaeology.md" -ItemType "file"
new-item -path $folder\ -Name "CD Diplomatics Archives Seals.md" -ItemType "file"
new-item -path $folder\ -Name "CE Technical Chronology Calendar.md" -ItemType "file"
new-item -path $folder\ -Name "CJ Numismatics.md" -ItemType "file"
new-item -path $folder\ -Name "CN Inscriptions Epigraphy.md" -ItemType "file"
new-item -path $folder\ -Name "CR Heraldry.md" -ItemType "file"
new-item -path $folder\ -Name "CS Genealogy.md" -ItemType "file"
new-item -path $folder\ -Name "CT Biography.md" -ItemType "file"
new-item -path $folder\ -Name "D History General.md" -ItemType "file"
new-item -path $folder\ -Name "DA Great Britain.md" -ItemType "file"
new-item -path $folder\ -Name "DAW Central Europe.md" -ItemType "file"
new-item -path $folder\ -Name "DB Austria Liechtenstein Hungary Czechoslovakia.md" -ItemType "file"
new-item -path $folder\ -Name "DC France Andorra Monaco.md" -ItemType "file"
new-item -path $folder\ -Name "DD Germany.md" -ItemType "file"
new-item -path $folder\ -Name "DE Greco Roman World.md" -ItemType "file"
new-item -path $folder\ -Name "DF Greece.md" -ItemType "file"
new-item -path $folder\ -Name "DG Italy Malta.md" -ItemType "file"
new-item -path $folder\ -Name "DH Low Countries Benelux Countries.md" -ItemType "file"
new-item -path $folder\ -Name "DJ Netherlands Holland.md" -ItemType "file"
new-item -path $folder\ -Name "DJK Eastern Europe General.md" -ItemType "file"
new-item -path $folder\ -Name "DK Russia Soviet Union Former Soviet Republics Poland.md" -ItemType "file"
new-item -path $folder\ -Name "DL Northern Europe Scandinavia.md" -ItemType "file"
new-item -path $folder\ -Name "DP Spain Portugal.md" -ItemType "file"
new-item -path $folder\ -Name "DQ Switzerland.md" -ItemType "file"
new-item -path $folder\ -Name "DR Balkan Peninsula.md" -ItemType "file"
new-item -path $folder\ -Name "DS Asia.md" -ItemType "file"
new-item -path $folder\ -Name "DT Africa.md" -ItemType "file"
new-item -path $folder\ -Name "DU Oceania South Seas.md" -ItemType "file"
new-item -path $folder\ -Name "DX Romanies.md" -ItemType "file"
new-item -path $folder\ -Name "No sub Class.md" -ItemType "file"
new-item -path $folder\ -Name "FC Canadian History.md" -ItemType "file"
new-item -path $folder\ -Name "G Geography General Atlases Maps.md" -ItemType "file"
new-item -path $folder\ -Name "GA Mathematical geography Cartography.md" -ItemType "file"
new-item -path $folder\ -Name "GB Physical geography.md" -ItemType "file"
new-item -path $folder\ -Name "GC Oceanography.md" -ItemType "file"
new-item -path $folder\ -Name "GE Environmental Sciences.md" -ItemType "file"
new-item -path $folder\ -Name "GF Human ecology Anthropogeography.md" -ItemType "file"
new-item -path $folder\ -Name "GN Anthropology.md" -ItemType "file"
new-item -path $folder\ -Name "GR Folklore.md" -ItemType "file"
new-item -path $folder\ -Name "GT Manners and customs General.md" -ItemType "file"
new-item -path $folder\ -Name "GV Recreation Leisure.md" -ItemType "file"
new-item -path $folder\ -Name "H Social sciences General.md" -ItemType "file"
new-item -path $folder\ -Name "HA Statistics.md" -ItemType "file"
new-item -path $folder\ -Name "HB Economic theory Demography.md" -ItemType "file"
new-item -path $folder\ -Name "HC Economic history and conditions.md" -ItemType "file"
new-item -path $folder\ -Name "HD Industries Land use Labor.md" -ItemType "file"
new-item -path $folder\ -Name "HE Transportation and communications.md" -ItemType "file"
new-item -path $folder\ -Name "HF Commerce.md" -ItemType "file"
new-item -path $folder\ -Name "HG Finance.md" -ItemType "file"
new-item -path $folder\ -Name "HJ Public finance.md" -ItemType "file"
new-item -path $folder\ -Name "HM Sociology General.md" -ItemType "file"
new-item -path $folder\ -Name "HN Social history and conditions Social problems Social reform.md" -ItemType "file"
new-item -path $folder\ -Name "HQ The family Marriage Women and Sexuality.md" -ItemType "file"
new-item -path $folder\ -Name "HS Societies secret benevolent etc.md" -ItemType "file"
new-item -path $folder\ -Name "HT Communities Classes Races.md" -ItemType "file"
new-item -path $folder\ -Name "HV Social pathology Social and public welfare Criminology.md" -ItemType "file"
new-item -path $folder\ -Name "HX Socialism Communism Anarchism.md" -ItemType "file"
new-item -path $folder\ -Name "J General legislative and executive papers.md" -ItemType "file"
new-item -path $folder\ -Name "JA Political science General.md" -ItemType "file"
new-item -path $folder\ -Name "JC Political theory.md" -ItemType "file"
new-item -path $folder\ -Name "JF Political institutions and public administration.md" -ItemType "file"
new-item -path $folder\ -Name "JJ Political institutions and public administration North America.md" -ItemType "file"
new-item -path $folder\ -Name "JK Political institutions and public administration United States.md" -ItemType "file"
new-item -path $folder\ -Name "JL Political institutions and public administration Canada Latin America etc.md" -ItemType "file"
new-item -path $folder\ -Name "JN Political institutions and public administration Europe.md" -ItemType "file"
new-item -path $folder\ -Name "JQ Political institutions and public administration Asia Africa Australia Pacific Area etc.md" -ItemType "file"
new-item -path $folder\ -Name "JS Local government Municipal government.md" -ItemType "file"
new-item -path $folder\ -Name "JV Colonies and colonization Emigration and immigration International migration.md" -ItemType "file"
new-item -path $folder\ -Name "JX International law see JZ and KZ obsolete.md" -ItemType "file"
new-item -path $folder\ -Name "JZ International relations.md" -ItemType "file"
new-item -path $folder\ -Name "K Law in general Comparative and uniform law Jurisprudence.md" -ItemType "file"
new-item -path $folder\ -Name "KB Religious law in general Comparative religious law Jurisprudence.md" -ItemType "file"
new-item -path $folder\ -Name "KBM Jewish law.md" -ItemType "file"
new-item -path $folder\ -Name "KBP Islamic law.md" -ItemType "file"
new-item -path $folder\ -Name "KBR History of canon law.md" -ItemType "file"
new-item -path $folder\ -Name "KBS Canon law of Eastern churches.md" -ItemType "file"
new-item -path $folder\ -Name "KBT Canon law of Eastern Rite Churches in Communion with the Holy See of Rome.md" -ItemType "file"
new-item -path $folder\ -Name "KBU Law of the Roman Catholic Church The Holy See.md" -ItemType "file"
new-item -path $folder\ -Name "KDK United Kingdom and Ireland.md" -ItemType "file"
new-item -path $folder\ -Name "KDZ America North America.md" -ItemType "file"
new-item -path $folder\ -Name "KE Canada.md" -ItemType "file"
new-item -path $folder\ -Name "KF United States.md" -ItemType "file"
new-item -path $folder\ -Name "KG Latin America Mexico and Central America West Indies Caribbean area.md" -ItemType "file"
new-item -path $folder\ -Name "KH South America.md" -ItemType "file"
new-item -path $folder\ -Name "KJ KKZ Europe.md" -ItemType "file"
new-item -path $folder\ -Name "KL KWX Asia and Eurasia Africa Pacific Area and Antarctica.md" -ItemType "file"
new-item -path $folder\ -Name "KU KUQ Law of Australia and New Zealand.md" -ItemType "file"
new-item -path $folder\ -Name "KZ Law of nations.md" -ItemType "file"
new-item -path $folder\ -Name "L Education General.md" -ItemType "file"
new-item -path $folder\ -Name "LA History of education.md" -ItemType "file"
new-item -path $folder\ -Name "LB Theory and practice of education.md" -ItemType "file"
new-item -path $folder\ -Name "LC Special aspects of education.md" -ItemType "file"
new-item -path $folder\ -Name "LD Individual institutions United States.md" -ItemType "file"
new-item -path $folder\ -Name "LE Individual institutions America except United States.md" -ItemType "file"
new-item -path $folder\ -Name "LF Individual institutions Europe.md" -ItemType "file"
new-item -path $folder\ -Name "LG Individual institutions Asia Africa Indian Ocean islands Australia New Zealand Pacific islands.md" -ItemType "file"
new-item -path $folder\ -Name "LH College and school magazines and papers.md" -ItemType "file"
new-item -path $folder\ -Name "LJ Student fraternities and societies United States.md" -ItemType "file"
new-item -path $folder\ -Name "LT Textbooks.md" -ItemType "file"
new-item -path $folder\ -Name "M Music.md" -ItemType "file"
new-item -path $folder\ -Name "ML Literature on music.md" -ItemType "file"
new-item -path $folder\ -Name "MT Instruction and study.md" -ItemType "file"
new-item -path $folder\ -Name "NA Architecture.md" -ItemType "file"
new-item -path $folder\ -Name "NB Sculpture.md" -ItemType "file"
new-item -path $folder\ -Name "NC Drawing Design Illustration.md" -ItemType "file"
new-item -path $folder\ -Name "ND Painting.md" -ItemType "file"
new-item -path $folder\ -Name "NE Print media.md" -ItemType "file"
new-item -path $folder\ -Name "NK Decorative arts.md" -ItemType "file"
new-item -path $folder\ -Name "NX Arts in general.md" -ItemType "file"
new-item -path $folder\ -Name "P Philology Linguistics.md" -ItemType "file"
new-item -path $folder\ -Name "PA Greek language and literature Latin language and literature.md" -ItemType "file"
new-item -path $folder\ -Name "PB Modern languages Celtic languages and literature.md" -ItemType "file"
new-item -path $folder\ -Name "PC Romanic languages.md" -ItemType "file"
new-item -path $folder\ -Name "PD Germanic languages Scandinavian languages.md" -ItemType "file"
new-item -path $folder\ -Name "PE English language.md" -ItemType "file"
new-item -path $folder\ -Name "PF West Germanic languages.md" -ItemType "file"
new-item -path $folder\ -Name "PG Slavic languages and literature Baltic languages Albanian language.md" -ItemType "file"
new-item -path $folder\ -Name "PH Uralic languages Basque language.md" -ItemType "file"
new-item -path $folder\ -Name "PJ Oriental languages and literatures.md" -ItemType "file"
new-item -path $folder\ -Name "PK Indo Iranian languages and literature.md" -ItemType "file"
new-item -path $folder\ -Name "PL Languages and literature of Eastern Asia Africa Oceania.md" -ItemType "file"
new-item -path $folder\ -Name "PM Hyperborean Native American and artificial languages.md" -ItemType "file"
new-item -path $folder\ -Name "PN Literature General.md" -ItemType "file"
new-item -path $folder\ -Name "PQ French literature Italian literature Spanish literature Portuguese literature.md" -ItemType "file"
new-item -path $folder\ -Name "PR English literature.md" -ItemType "file"
new-item -path $folder\ -Name "PS American literature.md" -ItemType "file"
new-item -path $folder\ -Name "PT Literature German Dutch Flemish Afrikaans Scandinavian Norse Icelandic and Norwegian Modern Icelandic Faroese Danish Norwegian Swedish.md" -ItemType "file"
new-item -path $folder\ -Name "PZ Fiction and juvenile belles lettres.md" -ItemType "file"
new-item -path $folder\ -Name "Q Science General.md" -ItemType "file"
new-item -path $folder\ -Name "QA Mathematics.md" -ItemType "file"
new-item -path $folder\ -Name "QB Astronomy.md" -ItemType "file"
new-item -path $folder\ -Name "QC Physics.md" -ItemType "file"
new-item -path $folder\ -Name "QD Chemistry.md" -ItemType "file"
new-item -path $folder\ -Name "QE Geology.md" -ItemType "file"
new-item -path $folder\ -Name "QH Natural history Biology.md" -ItemType "file"
new-item -path $folder\ -Name "QK Botany.md" -ItemType "file"
new-item -path $folder\ -Name "QL Zoology.md" -ItemType "file"
new-item -path $folder\ -Name "QM Human anatomy.md" -ItemType "file"
new-item -path $folder\ -Name "QP Physiology.md" -ItemType "file"
new-item -path $folder\ -Name "QR Microbiology.md" -ItemType "file"
new-item -path $folder\ -Name "R Medicine General.md" -ItemType "file"
new-item -path $folder\ -Name "RA Public aspects of medicine.md" -ItemType "file"
new-item -path $folder\ -Name "RB Pathology.md" -ItemType "file"
new-item -path $folder\ -Name "RC Internal medicine.md" -ItemType "file"
new-item -path $folder\ -Name "RD Surgery.md" -ItemType "file"
new-item -path $folder\ -Name "RE Ophthalmology.md" -ItemType "file"
new-item -path $folder\ -Name "RF Otorhinolaryngology.md" -ItemType "file"
new-item -path $folder\ -Name "RG Gynecology and Obstetrics.md" -ItemType "file"
new-item -path $folder\ -Name "RJ Pediatrics.md" -ItemType "file"
new-item -path $folder\ -Name "RK Dentistry.md" -ItemType "file"
new-item -path $folder\ -Name "RL Dermatology.md" -ItemType "file"
new-item -path $folder\ -Name "RM Therapeutics Pharmacology.md" -ItemType "file"
new-item -path $folder\ -Name "RS Pharmacy and materia medica.md" -ItemType "file"
new-item -path $folder\ -Name "RT Nursing.md" -ItemType "file"
new-item -path $folder\ -Name "RV Botanic Thomsonian and Eclectic medicine.md" -ItemType "file"
new-item -path $folder\ -Name "RX Homeopathy.md" -ItemType "file"
new-item -path $folder\ -Name "RZ Other systems of medicine.md" -ItemType "file"
new-item -path $folder\ -Name "S Agriculture General.md" -ItemType "file"
new-item -path $folder\ -Name "SB Horticulture Plant propagation Plant breeding.md" -ItemType "file"
new-item -path $folder\ -Name "SD Forestry Arboriculture Silviculture.md" -ItemType "file"
new-item -path $folder\ -Name "SF Animal husbandry Animal science.md" -ItemType "file"
new-item -path $folder\ -Name "SH Aquaculture Fisheries Angling.md" -ItemType "file"
new-item -path $folder\ -Name "SK Hunting.md" -ItemType "file"
new-item -path $folder\ -Name "T Technology General.md" -ItemType "file"
new-item -path $folder\ -Name "TA Engineering Civil engineering General.md" -ItemType "file"
new-item -path $folder\ -Name "TC Hydraulic engineering Ocean engineering.md" -ItemType "file"
new-item -path $folder\ -Name "TD Environmental technology Sanitary engineering.md" -ItemType "file"
new-item -path $folder\ -Name "TE Highway engineering Roads and pavements.md" -ItemType "file"
new-item -path $folder\ -Name "TF Railroad engineering and operation.md" -ItemType "file"
new-item -path $folder\ -Name "TG Bridges.md" -ItemType "file"
new-item -path $folder\ -Name "TH Building construction.md" -ItemType "file"
new-item -path $folder\ -Name "TJ Mechanical engineering and machinery.md" -ItemType "file"
new-item -path $folder\ -Name "TK Electrical engineering Electronics Nuclear engineering.md" -ItemType "file"
new-item -path $folder\ -Name "TL Motor vehicles Aeronautics Astronautics.md" -ItemType "file"
new-item -path $folder\ -Name "TN Mining engineering Metallurgy.md" -ItemType "file"
new-item -path $folder\ -Name "TP Chemical technology.md" -ItemType "file"
new-item -path $folder\ -Name "TR Photography.md" -ItemType "file"
new-item -path $folder\ -Name "TS Manufacturing engineering Mass production.md" -ItemType "file"
new-item -path $folder\ -Name "TT Handicrafts Arts and crafts.md" -ItemType "file"
new-item -path $folder\ -Name "TX Home economics.md" -ItemType "file"
new-item -path $folder\ -Name "U Military science General.md" -ItemType "file"
new-item -path $folder\ -Name "UA Armies Organization distribution military situation.md" -ItemType "file"
new-item -path $folder\ -Name "UB Military administration.md" -ItemType "file"
new-item -path $folder\ -Name "UC Military maintenance and transportation.md" -ItemType "file"
new-item -path $folder\ -Name "UD Infantry.md" -ItemType "file"
new-item -path $folder\ -Name "UE Cavalry Armor.md" -ItemType "file"
new-item -path $folder\ -Name "UF Artillery.md" -ItemType "file"
new-item -path $folder\ -Name "UG Military engineering Air forces.md" -ItemType "file"
new-item -path $folder\ -Name "UH Other military services.md" -ItemType "file"
new-item -path $folder\ -Name "V Naval science General.md" -ItemType "file"
new-item -path $folder\ -Name "VA Navies Organization distribution naval situation.md" -ItemType "file"
new-item -path $folder\ -Name "VB Naval administration.md" -ItemType "file"
new-item -path $folder\ -Name "VC Naval maintenance.md" -ItemType "file"
new-item -path $folder\ -Name "VD Naval seamen.md" -ItemType "file"
new-item -path $folder\ -Name "VE Marines.md" -ItemType "file"
new-item -path $folder\ -Name "VF Naval ordnance.md" -ItemType "file"
new-item -path $folder\ -Name "VG Minor services of navies.md" -ItemType "file"
new-item -path $folder\ -Name "VK Navigation Merchant marine.md" -ItemType "file"
new-item -path $folder\ -Name "VM Naval architecture Shipbuilding Marine engineering.md" -ItemType "file"
new-item -path $folder\ -Name "Z Books General Writing Paleography Book industries and trade Libraries Bibliography.md" -ItemType "file"
new-item -path $folder\ -Name "ZA Information resources materials.md" -ItemType "file"
